spring:
  application:
    name: spring-book
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
      url: ${datasource_url:jdbc:mysql://localhost:3306/spring-book?useSSL=false}
      username: ${db_user:root}
      password: ${db_password:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: ${db_ddl_auto:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        temp:
          use-jdbc-metadata: false
        ddl_auto: ${db_ddl_auto:none}
        globally_quoted_identifiers: true
    show-sql: false
  sql:
    init:
      platform: mysql
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mailUsername:oswaldo.adrian35@gmail.com}
    password: ${mailPassword:solzapobennprvbb}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: ${app_port:3001}
  servlet:
    context-path: /api/v1
servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
springbook:
  api:
    jwtSecret: ${jwtSecret:TH1S4VeRYs3cr3tSpr1nGb00k@P1k3Y}
    jwtAccessExpirationMs: ${jwtAccessExpirationMs:86400000}
    jwtRefreshExpirationMs: ${jwtRefreshExpirationMs:604800000}
    awsAccessKey: ${awsAccessKey:AKIAYZ5IZJSOOE43B3UQ}
    awsSecretKey: ${awsSecretKey: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}
    awsRegion: ${awsRegion:us-east-1}
    awsBucket: ${awsBucket:spring-book}
    s3BaseUrl: ${s3BaseUrl:https://spring-book.s3.amazonaws.com}
